### ISSUE TITLE
Labels don't seem to be working for me

### ISSUE THREAD

**Issue by pablote** [blendle/zapdriver#31]
Maybe I'm doing something wrong, this is my code:
```
logger, _ := zapdriver.NewProduction()
logger.Info("Test log message", zap.String("hello",  "world"))
```

And this logs to console:
```
{
  "severity": "INFO",
  "timestamp": "2020-05-18T17:04:30.725484-03:00",
  "caller": "redacted/main.go:32",
  "message": "Test log message",
  "hello": "world",
  "logging.googleapis.com/labels": {},
  "logging.googleapis.com/sourceLocation": {
    "file": "redacted/main.go",
    "line": "32",
    "function": "main.init.0"
  }
}
```

Shouldn't `hello:world` be on the labels section? Thanks

**Comment by JeanMertz** [comment]
Hey @pablote,

As you've noticed, fields don't get added to the `labels` object by default, as there are valid reasons to keep fields outside this object.

However, you can use `zapdriver.Label("hello", "world")` to have them namespaced as expected. 

This is assuming you are using `zapdriver.Core` (which you are, since you are using `zapdriver.NewProduction()`). If not, you will have to wrap your `zapdriver.Label`s in a top-level `zapdriver.Labels`.

You can [read the README](https://github.com/blendle/zapdriver#label) to learn more about this.

**Comment by pablote** [comment]
Ah ok. I was under the impression that as long as I was using the zapdriver core, all fields were gonna be added as labels. I'm not sure if I feel great about adding `zapdriver.Label` throughout my application, I figured it would be transparent somehow. Thanks for the clarification.

**Comment by JeanMertz** [comment]
@pablote A label is a very specific piece of information you attach to a Stackdriver-based log line. Usually, most of your log fields should not be added as labels (and in fact, labels only support strings, no other types).

I'd advise you to read the Stackdriver documentation, as I think you might have the wrong impression on what labels should be used for, they should definitely not be the default for adding new log fields.

See: https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry

Labels end up in the `labels` field:

> labels | map (key: string, value: string)
> Optional. A set of user-defined (key, value) data that provides additional information about the log entry.

Whereas regular log fields (such as your `zap.String("hello", "world")`) end up as `jsonPayload`:

>  jsonPayload | object (Struct format)
> The log entry payload, represented as a structure that is expressed as a JSON object.
